version: '3.8'

services:
  # Replace the prebuild godwoken-web3 with manual-build.
  #
  # 1. First you have to build godwoken-web3 manually and copy the result
  # artifacts to `docker/manual-artifacts/`:
  #
  #   ```
  #   make init MANUAL_BUILD_WEB3=true
  #   ```
  #
  # 2. Then start docker-compose service:
  #
  #   ```
  #   docker-compose -f docker/docker-compose.yml -f docker/manual-web3.compose.yml up -d web3
  #   ```
  web3:
    volumes:
      - ./manual-artifacts/godwoken-web3:/godwoken-web3:ro
