name: Godwoken Tests

on:
  push:
    branches: [develop]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:

jobs:
  godwoken-tests:
    uses: godwokenrises/godwoken-tests/.github/workflows/reusable-integration-test-v1.yml@develop
    with:
      extra_github_env: |
        GODWOKEN_KICKER_REPO=${{ github.repository }}
        GODWOKEN_KICKER_REF=${{ github.ref }}
        MANUAL_BUILD_GODWOKEN="true"
        MANUAL_BUILD_SCRIPTS="true"
        GODWOKEN_GIT_URL=https://github.com/keroro520/godwoken
        GODWOKEN_GIT_CHECKOUT=feat-withdrawal-finalized-timepoint
        SCRIPTS_GIT_URL="$GODWOKEN_GIT_URL"
        SCRIPTS_GIT_CHECKOUT="$GODWOKEN_GIT_CHECKOUT"
