name: WIP

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  godwoken-tests:
    uses: keroro520/godwoken-tests/.github/workflows/reusable-integration-test-v1.yml@89f42b15a41aa0abf1023a8cdb969179620c8181
    with:
      extra_github_env: |
        KICKER_REPO=${{ github.repository }}
        KICKER_REF=${{ github.ref }}
