name: Godwoken Tests

on:
  push:
    branches: [develop, master, ci, 'v1*', compatibility-changes]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:

jobs:
  godwoken-tests:
    uses: nervosnetwork/godwoken-tests/.github/workflows/reusable-integration-test-v1.yml@simplify-workflow
    with:
      extra_github_env: |
        GODWOKEN_KICKER_REPO=${{ github.repository }}
        GODWOKEN_KICKER_REF=${{ github.ref }}
        MANUAL_BUILD_POLYJUICE="true"
        POLYJUICE_GIT_URL=https://github.com/nervosnetwork/godwoken-polyjuice
        POLYJUICE_GIT_CHECKOUT=fef5a48
