name: WIP

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  godwoken-tests:
    uses: keroro520/godwoken-tests/.github/workflows/reusable-integration-test-v1.yml@ci-allow-fork-repo
    with:
      extra_github_env: |
        KICKER_REPO=${{ github.repository }}
        KICKER_REF=${{ github.ref }}
        MANUAL_BUILD_WEB3=true
        WEB3_GIT_URL=https://github.com/keroro520/godwoken-web3
        WEB3_GIT_CHECKOUT=merge-v1.1
