on:
  push:
    branches: [develop, master, ci, v1, compatibility-changes]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:

jobs:
  hardhat-simple-project:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Part 1. Deploy Local Network of Godwoken"
      - name: Checkout Godwoken-Kicker
        uses: actions/checkout@v2
      - run: git rev-parse HEAD
      - run: ./kicker init
      - run: ./kicker start
      - run: ./kicker info
      - run: ./kicker ps
      - run: ./kicker ps web3
      - run: ./kicker logs
      - run: ./kicker logs web3
      - run: ./kicker -- top
      - run: ./kicker -- exec -i ckb ls -l
      - run: ./kicker -- help
      - run: ./kicker deposit 0xCD1d13450cFA630728D0390C99957C6948BF7d19 1000
      - run: ./kicker get 0xCD1d13450cFA630728D0390C99957C6948BF7d19

      - run: echo "Part 2. Deploy A Simple Contract Using Hardhat"
      - run: git clone --depth=1 https://github.com/NomicFoundation/hardhat
      - run: npm install --save-dev hardhat @nomiclabs/hardhat-waffle
        working-directory: hardhat/packages/hardhat-core/sample-projects/basic/
      - name: Adapt hardhat.config.js to our local network of Godwoken
        run: |
          sed -i 's#solidity:#    networks: { gw_devnet_v1: { url: `http://127.0.0.1:8024`, accounts: [`0x9d5bc55413c14cf4ce360a6051eacdc0e580100a0d3f7f2f48f63623f6b05361`], } }, solidity:#g' hardhat.config.js
          cat hardhat.config.js
        working-directory: hardhat/packages/hardhat-core/sample-projects/basic/
      - run: npx hardhat accounts --network gw_devnet_v1
        working-directory: hardhat/packages/hardhat-core/sample-projects/basic/
      - run: npx hardhat compile
        working-directory: hardhat/packages/hardhat-core/sample-projects/basic/
      - run: npx hardhat test --network gw_devnet_v1
        working-directory: hardhat/packages/hardhat-core/sample-projects/basic/
      - run: npx hardhat run --network gw_devnet_v1 scripts/sample-script.js
        working-directory: hardhat/packages/hardhat-core/sample-projects/basic/

      - run: echo "Part3. Clean Up"
      - run: ./kicker stop
      - run: sudo ./kicker clean
      - run: ./kicker ps
